### PR TITLE
Swap cheerio with htmlparser2

### PR DESCRIPTION
**Pull request by vladimyr**
Hi Jannis 👋 

Thank you for making this useful package 👍 
I made some changes, hope you'll gonna like them.

Most important change is swapping [`cheerio`](https://npm.im/cheerio) with [`htmlparser2`](https://npm.im/htmlparser2). Reasoning behind this is because it significantly decreases install size of package. Compare following:
- [install size of cheerio (**2.76 MB**)](https://packagephobia.now.sh/result?p=cheerio)
- [install size of htmlparser2 (**401 kB**)](https://packagephobia.now.sh/result?p=htmlparser2)

Because `htmlparser2` is in fact used by `cheerio` this essentially means peeling off one layer of abstraction. It definitely results in _uglier_ code but that should be fine tradeoff keeping in mind gains in package size.

Other non-essential changes:
- configured ESLint (using [standard](https://standardjs.com) config because you obviously like it without semicolons 😉 )
- updated `.gitignore` with vscode folder
- updated Travis CI configuration (disabled linting on versions bellow `8` due to ESLint dropping support for those)
- upgraded babel cli & preset-env
- added code style & package size badges to readme

### CODE REVIEW

**Comment by derhuerst** [comment]
> Hi Jannis 👋 

Hey, thanks for your contribution!

> Most important change is swapping [`cheerio`](https://npm.im/cheerio) with [`htmlparser2`](https://npm.im/htmlparser2). Reasoning behind this is because it significantly decreases install size of package. Compare following:
> - [install size of cheerio (**2.76 MB**)](https://packagephobia.now.sh/result?p=cheerio)
> - [install size of htmlparser2 (**401 kB**)](https://packagephobia.now.sh/result?p=htmlparser2)
>
> Because `htmlparser2` is in fact used by `cheerio` this essentially means peeling off one layer of abstraction. It definitely results in _uglier_ code but that should be fine tradeoff keeping in mind gains in package size.

**Looking at the diff, this slightly uglier code is fine.** 👍 I'm fine with the trade-off.

**Please separate the other changes from the `cheerio` -> `htmlparser2` switch though!** This makes it easier for maintainers to review, decide which changes to adopt and revert specific changes, and easier for consumers of the library to figure what changed between versions.

> Other non-essential changes:
> - configured ESLint (using [standard](https://standardjs.com) config because you obviously like it without semicolons 😉 )

I tend use tooling like this gently and usually don't deem a linter necessary for a simple lib like this one. Also, I don't really see the value of linting code *style* in this case (but the value of catching bugs with a linter). In this case I'm fine with the change.

> - upgraded babel cli & preset-env

Thanks!

> - added code style & package size badges to readme

I don't really see the value of these TBH, but I'm fine with keeping them.

- Consuming a library, I don't really care about the style of its code; contributions to this lib will be very rare, as it's simple and focused.
- Package size really depends on which packages you already have, optimisations like dead code elimination (a.k.a. tree shaking), etc.

**Comment by vladimyr** [comment]
Thank you for quick review 🏃 

> **Please separate the other changes from the `cheerio` -> `htmlparser2` switch though!** This makes it easier for maintainers to review, decide which changes to adopt and revert specific changes, and easier for consumers of the library to figure what changed between versions.

That is valid argument 👍 I'm usually not here you go - giant commit/PR - type of guy but I also tend to group stuff together based on subjective limits. 🙃 
However I'm not sure what to do now. I can easily chunk this into multiple PRs but reading your comment to the end made me realize you are ok with all introduced changes so do you still want me to do it or you left this as future reference? 🤔 

> I tend use tooling like this gently and usually don't deem a linter necessary for a simple lib like this one. Also, I don't really see the value of linting code _style_ in this case (but the value of catching bugs with a linter). In this case I'm fine with the change.

This is ofc subjective topic and I understand and appreciate your position. Let me just give you my (counter)arguments:
1. Having linter even for small libs reduces potential bikeshedding when dealing with outside contributions (even the smallest possible ones) thus reducing contribution friction.
2. Like it or not ESLint is de-facto standard javascript linter and it made [JavaScript Code Style checker](https://jscs-dev.github.io/) part of its codebase long ago. That means ESLint devs are pretty clear that (their) linter is in fact both static code analyzer and code style checker 🙃 

> I don't really see the value of these TBH, but I'm fine with keeping them.
> 
> * Consuming a library, I don't really care about the style of its code; contributions to this lib will be very rare, as it's simple and focused.

Rare contributions still doesn't mean no contributions at all and I see it as more-less standard way of communicating expectations with potential contributors. If you still think it has no place inside readme I'll gladly cut it out.

> * Package size really depends on which packages you already have, optimisations like dead code elimination (a.k.a. tree shaking), etc.

Now I simply don't get it 😕 What you said holds true for **bundle** size, package size is invariable. In the same time this is node only module due to lack of CORS support on flickr side (which probably won't change any time soon) thus no bundling is expected to happen unless someone uses webpack on server side which is pretty exotic and not a good idea for multiple reasons not related to this conversation.
That being said I think it is important to point out installation cost of package because every kB/MB adds to cumulative install size/time of consumer app.

**Comment by derhuerst** [comment]
>> **Please separate the other changes from the `cheerio` -> `htmlparser2` switch though!**
>
> [...] I'm not sure what to do now. I can easily chunk this into multiple PRs but reading your comment to the end made me realize you are ok with all introduced changes so do you still want me to do it or you left this as future reference? 🤔

Just put them in separate commits (with proper commit messages).

> Now I simply don't get it 😕 What you said holds true for **bundle** size, package size is invariable.

Yes true, I meant bundle size.

> In the same time this is node only module due to lack of CORS support on flickr side [...].

That is a bold assumption. 😉 There is Electron, browser plugins, Service-Worker-based environments, etc. This is why I use `fetch-ponyfill` instead of `node-fetch`.

**Comment by vladimyr** [comment]
> Just put them in separate commits (with proper commit messages).

Done ✅ 

> That is a bold assumption. 😉 There is Electron, browser plugins, Service-Worker-based environments, etc. This is why I use `fetch-ponyfill` instead of `node-fetch`.

I see what you did there :shipit:

**Comment by derhuerst** [comment]
Thanks for your contribution! Published as `flickr-photo-url@2.1.0`.

**Pull request merged**
